{% set name = "pyqg" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyqg/pyqg/archive/v{{ version }}.tar.gz
  sha256: 7da202969956330a97120db94bb000a4d5cda0974505f986d32834e1dcc16aec

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - libgomp  # [linux]
  host:
    - python
    - pip
    - cython
    - numpy
    - pyfftw
  run:
    - python
    - pyfftw
    - {{ pin_compatible('numpy') }}
    - libgomp  # [linux]

test:
  source_files:
    - pyqg/tests
  requires:
    - pytest
    - future
    - xarray
  imports:
    - pyqg
    - pyqg.kernel
  commands:
    - pytest pyqg
  # Cannot run pip check there is a bogus dependency on cython at runtime.
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/pyqg/pyqg
  summary: python quasigeostrophic model
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Pyqg is a python solver for quasigeostrophic systems. Quasigeostophic
    equations are an approximation to the full fluid equations of motion in
    the limit of strong rotation and stratitifcation and are most applicable
    to geophysical fluid dynamics problems.
  doc_url: https://pyqg.readthedocs.io/en/latest/
  dev_url: https://github.com/pyqg/pyqg

extra:
  recipe-maintainers:
    - rabernat
    - mfjansen
